project:
  type: website
  output-dir: .
  
website:
  title: "My website"
  navbar:
    left:
      - href: index.html
        text: Home
        
      - href: about.html
      
      - href: dyna_adaptative.html
        text: Dynamique adaptative
      
      - href: coffee_micorizia_map.html
        text: Dynamique adaptative

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



