project:
  type: website
  output-dir: .
  
website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: dyna_adaptative.qmd
        text: Dynamique adaptative

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



